# Generated by Django 3.1.4 on 2020-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('eastings', models.IntegerField(blank=True, null=True)),
                ('northings', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('nhs_ha', models.CharField(blank=True, max_length=30)),
                ('european_electoral_region', models.CharField(blank=True, max_length=30)),
                ('primary_care_trust', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('lsoa', models.CharField(blank=True, max_length=30)),
                ('msoa', models.CharField(blank=True, max_length=30)),
                ('incode', models.CharField(blank=True, max_length=30)),
                ('outcode', models.CharField(blank=True, max_length=30)),
                ('parliamentary_constituency', models.CharField(blank=True, max_length=30)),
                ('admin_district', models.CharField(blank=True, max_length=30)),
                ('parish', models.CharField(blank=True, max_length=30)),
                ('admin_county', models.CharField(blank=True, max_length=30)),
                ('admin_ward', models.CharField(blank=True, max_length=30)),
                ('ced', models.CharField(blank=True, max_length=30)),
                ('ccg', models.CharField(blank=True, max_length=30)),
                ('nuts', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('postcodes', models.ManyToManyField(blank=True, related_name='postcodes', to='postcode.Postcode')),
            ],
        ),
    ]
