# Generated by Django 3.1.4 on 2020-12-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0002_auto_20201224_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='admin_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='admin_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='admin_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='ccg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='ced',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='european_electoral_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='incode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='lsoa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='msoa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='nhs_ha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='nuts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='outcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='parish',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='parliamentary_constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='primary_care_trust',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
