version: '3.5'

services:
  django-project:
    container_name: DjangoProject
    build: ./django_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project/near_postcode/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - envs/dev_django.env
    entrypoint: ["/entrypoint.sh"]

  fastapi-project:
    container_name: FastAPIProject
    build: ./fastapi_project
    volumes:
      - ./fastapi_project/loader_file/:/loader_file 
    ports:
      - 8001:80

  db:
    container_name: Postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/dev_postgres.env

volumes:
  postgres_data:
